# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back', 'rb'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch', 'AngleX', 'AngleY'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [1]:
%pylab inline
import pickle
from os import listdir, path
import numpy as np
from sklearn import svm, metrics

ROBOT_POSE_DATA_DIR = 'robot_pose_data'

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print(classes)

['Back', 'Belly', 'Crouch', 'Frog', 'HeadBack', 'Knee', 'Left', 'Right', 'Sit', 'Stand', 'StandInit']


In [3]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    # YOUR CODE HERE
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    data = pickle.load(open(filename, 'rb'))
    target = [i] * len(data)
    return data, target

In [4]:
# load all the data
all_data = []
all_target = []
# YOUR CODE HERE
for i in range(len(classes)):
    temp_data, temp_target = load_pose_data(i)
    all_data.extend(temp_data)
    all_target.extend(temp_target)
all_data = np.asarray(all_data)
all_target = np.asarray(all_target)

print('total number of data', len(all_data))
print('total number of targets', len(all_target))
all_data

total number of data 223
total number of targets 223


array([[-0.05058002, -0.22698998, -0.8298521 , ...,  1.8945322 ,
        -0.0089925 , -1.51652062],
       [-0.05058002, -0.22698998, -0.8298521 , ...,  1.89606619,
        -0.00688345, -1.52035582],
       [-0.05058002, -0.22698998, -0.8298521 , ...,  1.8945322 ,
        -0.00688345, -1.52016413],
       ...,
       [-0.02757001,  0.00464392, -0.57367396, ...,  0.91737413,
        -0.01169664,  0.04486877],
       [-0.02910399,  0.00464392, -0.57367396, ...,  0.91737413,
        -0.013614  ,  0.04084188],
       [-0.24693203,  0.12582994, -0.28681612, ...,  1.01094818,
         0.01514834,  0.11869175]])

In [5]:
# shuffule data
permutation = np.random.permutation(len(all_data))
n_training_data = int(len(all_data) * 0.7)
training_data = permutation[:n_training_data]

## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [6]:
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [7]:
# YOUR CODE HERE
clf.fit(all_data[training_data], all_target[training_data])

SVC(C=100.0, gamma=0.001)

### predicting

In [8]:
clf.predict(all_data[training_data]), all_target[training_data]

(array([10,  1,  8,  8, 10,  9, 10,  1,  7,  0,  5,  1,  2,  8,  9,  1,  1,
         0,  7,  3,  5,  8,  0,  8, 10,  4,  7,  6, 10,  2,  2,  1, 10,  2,
         8, 10,  2,  9,  4,  8,  0,  2,  2, 10,  6,  6,  6,  6,  0,  8,  6,
         2,  1, 10,  5, 10,  3,  0,  9,  2,  3,  7, 10, 10,  0,  4, 10,  1,
         5,  4, 10,  4,  2,  8,  2,  4,  2, 10,  2, 10,  9,  1,  8,  7, 10,
         5,  2,  8,  8,  0,  4,  1, 10,  8,  2,  2, 10,  6,  3,  5,  9,  2,
         6,  3,  0,  2, 10, 10, 10,  0,  6,  0, 10,  8,  0, 10, 10, 10,  7,
         2, 10,  6,  2,  2, 10, 10, 10,  8,  1,  5, 10,  2,  4,  9, 10,  0,
         1,  8,  8,  6,  3,  0,  5,  8,  9,  6,  6,  2, 10,  6, 10, 10,  7,
        10,  0,  0]),
 array([10,  1,  8,  8, 10,  9, 10,  1,  7,  0,  5,  1,  2,  8,  9,  1,  1,
         0,  7,  3,  5,  8,  0,  8, 10,  4,  7,  6, 10,  2,  7,  1, 10,  2,
         8, 10,  2,  9,  4,  8,  0,  2,  2, 10,  6,  6,  6,  6,  0,  8,  6,
         2,  1, 10,  5, 10,  3,  0,  9,  2,  3,  7, 10, 10,  0,  4

In [10]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

In [12]:
expected = []
predicted = []
# YOUR CODE HERE
expected = all_target[training_data]
predicted = clf.predict(all_data[training_data])

evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        12
           2       0.96      1.00      0.98        22
           3       1.00      1.00      1.00         6
           4       1.00      1.00      1.00         8
           5       1.00      1.00      1.00         8
           6       1.00      1.00      1.00        14
           7       1.00      0.88      0.93         8
           8       1.00      1.00      1.00        18
           9       1.00      1.00      1.00         8
          10       1.00      1.00      1.00        36

    accuracy                           0.99       156
   macro avg       1.00      0.99      0.99       156
weighted avg       0.99      0.99      0.99       156


Confusion matrix:
[[16  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0]
 [ 0  0 22  0  0  0  0  0  0  0  0]
 [ 0  0  0  6  0  0  0  0  0  0  0]
 

## 4. Evaluate on the test data

In [83]:
expected = []
predicted = []
# YOUR CODE HERE

evaluate(expected, predicted)

Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         5
          1       1.00      1.00      1.00         3
          2       1.00      1.00      1.00         5
          3       1.00      1.00      1.00         5
          4       0.91      1.00      0.95        10
          5       1.00      1.00      1.00         4
          6       1.00      1.00      1.00         2
          7       1.00      0.75      0.86         4
          8       1.00      1.00      1.00         8
          9       1.00      1.00      1.00         3
         10       1.00      1.00      1.00        11

avg / total       0.98      0.98      0.98        60


Confusion matrix:
[[ 5  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0  0  0  0  0]
 [ 0  0  5  0  0  0  0  0  0  0  0]
 [ 0  0  0  5  0  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0]
 [ 0  0  0  0 

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [13]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
pickle.dump(clf, open(ROBOT_POSE_CLF, 'wb'))

Then, in the application we can load the trained classifier again.

In [14]:
clf2 = pickle.load(open(ROBOT_POSE_CLF))
clf2.predict(all_data[-1]), all_target[-1]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 43: character maps to <undefined>